spring:
  datasource:
    url: jdbc:postgresql://localhost:5025/ninja-config-db
    username: ninja
    password: ninja
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/liquibase/db.changelog-master.yml