version: "3.9"

services:
  magic-zookeeper:
    container_name: $APPLICATION_NAME-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: always
  magic-kafka:
    container_name: $APPLICATION_NAME-kafka
    image: wurstmeister/kafka
    ports:
      - $KAFKA_PORT:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: $KAFKA_HOST_NAME
      KAFKA_ADVERTISED_PORT: $KAFKA_PORT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms128M"
      KAFKA_MESSAGE_MAX_BYTES: 16777216
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always